export const tableName = {
  companies: process.env.COMPANIES_TABLE || "companies",
  employees: process.env.EMPLOYEES_TABLE || "employees",
  activities: process.env.ACTIVITIES_TABLE || "activities",
  pendingApprovals: process.env.PENDING_APPROVAL_TABLE || "pending_approvals",
  appAuditLogs: process.env.APP_AUDIT_LOGS_TABLE || "app_audit_logs",
  reminders: process.env.REMINDERS_TABLE || "reminders",
  notifications: process.env.NOTIFICATIONS_TABLE || "notifications",
  authTokens: process.env.AUTH_TOKENS_TABLE || "auth_tokens",
  jobs: process.env.JOBS_TABLE || "jobs",
  updateHistory: process.env.UPDATE_HISTORY_TABLE || "update_history",
  teams: process.env.TEAMS || "teams",
  accessPermissions: process.env.ACCESS_PERMISSIONS_TABLE || "access_permissions",
  // emails: process.env.EMAILS || "emails",
  // emailHistory: process.env.EMAIL_HISTORY || "email_history",
  emailList: process.env.EMAIL_LIST || "email_lists",
  employeeCompanyInteraction: process.env.EMPLOYEE_COMPANY_INTERACTIONS || "employee_company_interactions",
};
